embeddings {
  tensor_name: "ticker:00009"
  metadata_path: "00009/ticker/metadata.tsv"
  tensor_path: "00009/ticker/tensors.tsv"
}
embeddings {
  tensor_name: "category:00009"
  metadata_path: "00009/category/metadata.tsv"
  tensor_path: "00009/category/tensors.tsv"
}
embeddings {
  tensor_name: "series_ticker:00009"
  metadata_path: "00009/series_ticker/metadata.tsv"
  tensor_path: "00009/series_ticker/tensors.tsv"
}
