embeddings {
  tensor_name: "ticker:00027"
  metadata_path: "00027/ticker/metadata.tsv"
  tensor_path: "00027/ticker/tensors.tsv"
}
embeddings {
  tensor_name: "category:00027"
  metadata_path: "00027/category/metadata.tsv"
  tensor_path: "00027/category/tensors.tsv"
}
embeddings {
  tensor_name: "series_ticker:00027"
  metadata_path: "00027/series_ticker/metadata.tsv"
  tensor_path: "00027/series_ticker/tensors.tsv"
}
